#!/usr/bin/env sh
set -eu

REPO="${REPO:-codestutis/cmdfreq}"
BINARY="${BINARY:-cmdfreq}"
VERSION="${VERSION:-latest}"
BIN_DIR="${BIN_DIR:-}"
CONFIG_DIR=""
SHELL_NAME=""

CONFIG_BEGIN="# >>> cmdfreq >>>"
CONFIG_END="# <<< cmdfreq <<<"

need() {
	if ! command -v "$1" >/dev/null 2>&1; then
		echo "error: $1 is required" >&2
		exit 1
	fi
}

validate_environment() {
	if [ -z "${HOME:-}" ]; then
		echo "error: HOME is required" >&2
		exit 1
	fi
	if [ -z "${SHELL:-}" ]; then
		echo "error: SHELL is required; cmdfreq supports bash and zsh" >&2
		exit 1
	fi

	SHELL_NAME="${SHELL##*/}"
	case "$SHELL_NAME" in
		bash | zsh) ;;
		*)
			echo "error: unsupported shell: $SHELL_NAME; cmdfreq supports bash and zsh" >&2
			exit 1
			;;
	esac

	if [ -z "$BIN_DIR" ]; then
		BIN_DIR="$HOME/.local/bin"
	fi
	CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/cmdfreq"
}

detect_os() {
	case "$(uname -s)" in
		Darwin) echo "Darwin" ;;
		Linux) echo "Linux" ;;
		CYGWIN* | MINGW* | MSYS*)
			echo "error: native Windows is not supported; use WSL with bash/zsh history" >&2
			exit 1
			;;
		*)
			echo "error: unsupported OS: $(uname -s)" >&2
			exit 1
			;;
	esac
}

detect_arches() {
	case "$(uname -m)" in
		x86_64 | amd64) echo "x86_64 amd64" ;;
		arm64 | aarch64) echo "arm64" ;;
		*)
			echo "error: unsupported CPU architecture: $(uname -m)" >&2
			exit 1
			;;
	esac
}

download() {
	url="$1"
	out="$2"

	if command -v curl >/dev/null 2>&1; then
		curl -fsSL "$url" -o "$out"
	elif command -v wget >/dev/null 2>&1; then
		wget -q "$url" -O "$out"
	else
		echo "error: curl or wget is required" >&2
		exit 1
	fi
}

install_binary() {
	src="$1"
	dst="$BIN_DIR/$BINARY"

	if ! mkdir -p "$BIN_DIR"; then
		echo "error: could not create $BIN_DIR" >&2
		exit 1
	fi

	chmod +x "$src"
	if [ -w "$BIN_DIR" ]; then
		mv "$src" "$dst"
	else
		echo "error: $BIN_DIR is not writable; choose a user-writable BIN_DIR" >&2
		exit 1
	fi
}

shell_quote() {
	printf "'"
	printf '%s' "$1" | sed "s/'/'\\\\''/g"
	printf "'"
}

write_shell_config() {
	config_file="$CONFIG_DIR/${SHELL_NAME}rc"
	new_config="$tmp/shell-config.new"
	quoted_bin_dir="$(shell_quote "$BIN_DIR")"

	mkdir -p "$CONFIG_DIR"
	{
		echo "# Generated by the cmdfreq installer."
		printf 'CMDFREQ_BIN_DIR=%s\n' "$quoted_bin_dir"
		cat <<'EOF'
case ":${PATH:-}:" in
	*":$CMDFREQ_BIN_DIR:"*) ;;
	*) export PATH="$CMDFREQ_BIN_DIR${PATH:+:$PATH}" ;;
esac
unset CMDFREQ_BIN_DIR
EOF

		if [ "$SHELL_NAME" = "zsh" ]; then
			cat <<'EOF'
export HISTFILE="${HISTFILE:-$HOME/.zsh_history}"
case ${HISTSIZE:-} in
	'' | *[!0-9]*) HISTSIZE=10000 ;;
	*) if [ "$HISTSIZE" -lt 10000 ]; then HISTSIZE=10000; fi ;;
esac
case ${SAVEHIST:-} in
	'' | *[!0-9]*) SAVEHIST=10000 ;;
	*) if [ "$SAVEHIST" -lt 10000 ]; then SAVEHIST=10000; fi ;;
esac
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
EOF
		else
			cat <<'EOF'
export HISTFILE="${HISTFILE:-$HOME/.bash_history}"
case ${HISTSIZE:-} in
	'' | *[!0-9]*) HISTSIZE=10000 ;;
	*) if [ "$HISTSIZE" -lt 10000 ]; then HISTSIZE=10000; fi ;;
esac
case ${HISTFILESIZE:-} in
	'' | *[!0-9]*) HISTFILESIZE=10000 ;;
	*) if [ "$HISTFILESIZE" -lt 10000 ]; then HISTFILESIZE=10000; fi ;;
esac
unset HISTCONTROL
shopt -s histappend

__cmdfreq_history_sync() {
	builtin history -a 2>/dev/null || :
	builtin history -n 2>/dev/null || :
}

case "$(declare -p PROMPT_COMMAND 2>/dev/null || :)" in
	"declare -a "*)
		_cmdfreq_prompt_found=false
		for _cmdfreq_prompt in "${PROMPT_COMMAND[@]}"; do
			if [ "$_cmdfreq_prompt" = "__cmdfreq_history_sync" ]; then
				_cmdfreq_prompt_found=true
				break
			fi
		done
		if [ "$_cmdfreq_prompt_found" = false ]; then
			PROMPT_COMMAND+=(__cmdfreq_history_sync)
		fi
		unset _cmdfreq_prompt _cmdfreq_prompt_found
		;;
	*)
		case ";${PROMPT_COMMAND:-};" in
			*";__cmdfreq_history_sync;"*) ;;
			*) PROMPT_COMMAND="__cmdfreq_history_sync${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
		esac
		;;
esac
EOF
		fi
	} >"$new_config"

	if [ ! -f "$config_file" ] || ! cmp -s "$new_config" "$config_file"; then
		cat "$new_config" >"$config_file"
		chmod 0644 "$config_file"
	fi
	SHELL_CONFIG_FILE="$config_file"
}

write_startup_file() {
	rc_file="$1"
	new_rc="$tmp/startup.new"
	quoted_config="$(shell_quote "$SHELL_CONFIG_FILE")"

	mkdir -p "${rc_file%/*}"
	if [ -f "$rc_file" ]; then
		awk -v begin="$CONFIG_BEGIN" -v end="$CONFIG_END" '
			$0 == begin { skipping = 1; next }
			$0 == end { skipping = 0; next }
			!skipping { print }
		' "$rc_file" >"$new_rc"
	else
		: >"$new_rc"
	fi

	{
		echo "$CONFIG_BEGIN"
		if [ "$SHELL_NAME" = "bash" ]; then
			echo 'if [ -n "${BASH_VERSION:-}" ]; then'
		else
			echo 'if [ -n "${ZSH_VERSION:-}" ]; then'
		fi
		printf '  CMDFREQ_SHELL_CONFIG=%s\n' "$quoted_config"
		echo '  if [ -r "$CMDFREQ_SHELL_CONFIG" ]; then'
		echo '    . "$CMDFREQ_SHELL_CONFIG"'
		echo '  fi'
		echo '  unset CMDFREQ_SHELL_CONFIG'
		echo 'fi'
		echo "$CONFIG_END"
	} >>"$new_rc"

	if [ -f "$rc_file" ] && cmp -s "$new_rc" "$rc_file"; then
		return
	fi
	if [ -f "$rc_file" ] && [ ! -e "$rc_file.cmdfreq.bak" ]; then
		cp "$rc_file" "$rc_file.cmdfreq.bak"
	fi
	cat "$new_rc" >"$rc_file"
}

configure_shell() {
	write_shell_config

	if [ "$SHELL_NAME" = "zsh" ]; then
		write_startup_file "${ZDOTDIR:-$HOME}/.zshrc"
		return
	fi

	write_startup_file "$HOME/.bashrc"
	login_rc=""
	for candidate in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
		if [ -f "$candidate" ]; then
			login_rc="$candidate"
			break
		fi
	done
	if [ -z "$login_rc" ]; then
		login_rc="$HOME/.bash_profile"
	fi
	write_startup_file "$login_rc"
}

main() {
	validate_environment
	need uname
	need tar
	need mktemp
	need find
	need tr
	need sed
	need awk
	need cmp
	need cp
	need head

	os="$(detect_os)"
	os_lower="$(printf '%s' "$os" | tr '[:upper:]' '[:lower:]')"
	arches="$(detect_arches)"
	tmp="$(mktemp -d)"
	trap 'rm -rf "$tmp"' EXIT INT TERM

	if [ "$VERSION" = "latest" ]; then
		base_url="https://github.com/$REPO/releases/latest/download"
	else
		base_url="https://github.com/$REPO/releases/download/$VERSION"
	fi

	archive="$tmp/$BINARY.tar.gz"
	downloaded=""
	for arch in $arches; do
		for name in \
			"${BINARY}_${os}_${arch}.tar.gz" \
			"${BINARY}_${os}_${arch}.tgz" \
			"${BINARY}_${os_lower}_${arch}.tar.gz" \
			"${BINARY}_${os_lower}_${arch}.tgz"
		do
			url="$base_url/$name"
			if download "$url" "$archive" >/dev/null 2>&1; then
				downloaded="$url"
				break 2
			fi
		done
	done

	if [ -z "$downloaded" ]; then
		echo "error: could not find a release archive for $os/$(uname -m)" >&2
		echo "looked under: $base_url" >&2
		exit 1
	fi

	tar -xzf "$archive" -C "$tmp"
	bin_path="$(find "$tmp" -type f -name "$BINARY" | head -n 1)"
	if [ -z "$bin_path" ]; then
		echo "error: archive did not contain $BINARY" >&2
		exit 1
	fi

	install_binary "$bin_path"
	configure_shell

	echo "installed $BINARY to $BIN_DIR"
	echo "configured $SHELL_NAME using $SHELL_CONFIG_FILE"
	echo "open a new terminal to start using $BINARY"
}

main "$@"
